sudo:  false

git:
  submodules: false
  depth: 1

language:  cpp
compiler:  gcc

install:  true

after_success:
  - ./a.out

notifications:
  email: false

matrix:
  include:
    - os: linux
      compiler: gcc
      script:
        - g++ a.cpp
    - os: osx
      compiler: clang
      script:
        - clang++ a.cpp
    - language: android
      android:
        components:
          - tools
          - platform-tools
          - android-21
          - sys-img-armeabi-v7a-android-21
